clear

load series_selection_H.01_beta.99_1000.mat

betas = {0.5 0.99 1.5};

%%% sort the vectors in ascending order; take bottom 9 middle 9, top 9
for i_b = 1:3
    beta = betas{i_b};
    sorted_series_pred_r = sort(series_pred_r{i_b});
     
    [minVals minInds] = intersect(series_pred_r{i_b},sorted_series_pred_r(1:5));
    [maxVals maxInds] = intersect(series_pred_r{i_b},sorted_series_pred_r(996:1000));
    [medVals medInds] = intersect(series_pred_r{i_b},sorted_series_pred_r(498:502));
   
    inds = [minInds' maxInds' medInds'];

    series_rp{i_b}      = series_r{i_b}(inds',:);
    series_pred_rp{i_b} = series_pred_r{i_b}(inds',:);
    pred_err_rp{i_b}    = pred_err_r{i_b}(inds',:);

% % plot the ranges for the series generated by converging_prediction
% % alongside the desired range value
% figure; hold on;
% plot([mean(ranges) mean(ranges)],[0 300],'g-','LineWidth',3)
% plot([r_target r_target],[0 300],'r-','LineWidth',3)
% hist(ranges);
% % set(h,'XScale','log');
% plot([mean(ranges) mean(ranges)],[0 300],'g-','LineWidth',3)
% plot([r_target r_target],[0 300],'r-','LineWidth',3)
% 
% legend('mean range value','desired range value');
% title(['distribution of ranges, beta = ' num2str(beta)]);
% xlabel('range')

% plot the ranges for the series generated by converging_prediction
% alongside the desired range value
% % % % figure; hold on;
% % % % h=20;
% % % % plot([median(ranges) median(ranges)],[0 h],'g-','LineWidth',2)
% % % % plot([r_target r_target],[0 h],'r-','LineWidth',2)
% % % % hist(ranges);
% % % % % set(h,'XScale','log');
% % % % plot([median(ranges) median(ranges)],[0 h],'g-','LineWidth',2)
% % % % plot([r_target r_target],[0 h],'r-','LineWidth',2)
% % % % 
% % % % legend(['median range value = ' num2str(median(ranges))],['desired range value = ' num2str((r_target))]);
% % % % title(['distribution of ranges (log scale), beta = ' num2str(beta) ', sigma2 = ' num2str(sigma2)]);
% % % % xlabel('range (log scale)')

% % plot the series that have ranges within r_delta of r_target
% figure; hold on;
% for j=1:sum(inRange)
%     plot(1:k,series_r{i_b}(j,:),'b-');
%     plot(k+1,series_pred_r{i_b}(j),'r.');
% end
% title(['selected for range, beta = ' num2str(beta)])


% plot the series that have ranges within r_delta of r_target
% and have the max, min, and median series prediction values
figure;
col = {'r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g' 'g' 'b' 'b' 'b' 'b' 'b'};
% subplot(211); hold on;
hold on;
for j = 1:length(inds)
    plot(1:k, series_rp{i_b}(j,:), [col{j} '-'],'LineWidth',2);
    plot(k+1, series_pred_rp{i_b}(j), [col{j} '*'], 'MarkerSize',5);
end
title(['selected for range and predicted sample, beta = ' num2str(beta)])


end
save('series_selection_5TrialsPerBeta_jenn.mat','series_rp','series_pred_rp','pred_err_rp');
